//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.NET_start.ProductServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductServiceRef.IProjectServiceOf_Product")]
    public interface IProjectServiceOf_Product {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/GetAll", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/GetAllResponse")]
        DbModels.Production.Product[] GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/GetAll", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/GetAllResponse")]
        System.Threading.Tasks.Task<DbModels.Production.Product[]> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Get", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/GetResponse")]
        DbModels.Production.Product Get(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Get", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/GetResponse")]
        System.Threading.Tasks.Task<DbModels.Production.Product> GetAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Create", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/CreateResponse")]
        void Create(DbModels.Production.Product item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Create", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/CreateResponse")]
        System.Threading.Tasks.Task CreateAsync(DbModels.Production.Product item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Update", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/UpdateResponse")]
        void Update(DbModels.Production.Product item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Update", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/UpdateResponse")]
        System.Threading.Tasks.Task UpdateAsync(DbModels.Production.Product item);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Delete", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/DeleteResponse")]
        void Delete(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProjectServiceOf_Product/Delete", ReplyAction="http://tempuri.org/IProjectServiceOf_Product/DeleteResponse")]
        System.Threading.Tasks.Task DeleteAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProjectServiceOf_ProductChannel : ASP.NET_start.ProductServiceRef.IProjectServiceOf_Product, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProjectServiceOf_ProductClient : System.ServiceModel.ClientBase<ASP.NET_start.ProductServiceRef.IProjectServiceOf_Product>, ASP.NET_start.ProductServiceRef.IProjectServiceOf_Product {
        
        public ProjectServiceOf_ProductClient() {
        }
        
        public ProjectServiceOf_ProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProjectServiceOf_ProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceOf_ProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProjectServiceOf_ProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public DbModels.Production.Product[] GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<DbModels.Production.Product[]> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public DbModels.Production.Product Get(int id) {
            return base.Channel.Get(id);
        }
        
        public System.Threading.Tasks.Task<DbModels.Production.Product> GetAsync(int id) {
            return base.Channel.GetAsync(id);
        }
        
        public void Create(DbModels.Production.Product item) {
            base.Channel.Create(item);
        }
        
        public System.Threading.Tasks.Task CreateAsync(DbModels.Production.Product item) {
            return base.Channel.CreateAsync(item);
        }
        
        public void Update(DbModels.Production.Product item) {
            base.Channel.Update(item);
        }
        
        public System.Threading.Tasks.Task UpdateAsync(DbModels.Production.Product item) {
            return base.Channel.UpdateAsync(item);
        }
        
        public void Delete(int id) {
            base.Channel.Delete(id);
        }
        
        public System.Threading.Tasks.Task DeleteAsync(int id) {
            return base.Channel.DeleteAsync(id);
        }
    }
}
